### ISSUE TITLE
Adding a close button

### ISSUE THREAD

**Issue by Janaue** [qimasho/thread-media-viewer#1]
Can you add a close button for the picture and media player/ I am talking about when I click the title of a webm or gif, the video starts playing at the top right, but then I dont know how to close it

**Comment by qimasho** [comment]
It's in Help section -> Mouse Controls: Right mouse button gesture down to close media view.

Or a shortcut Shift+F.

I doesn't feel right to add a close button, since none that is aware of the down gesture would ever use it. It'd be there just for people that don't know about it yet, but it would clutter the interface for everyone.

I might add some help tooltip when people are hovering viewer with button to hide it permanently.

**Comment by qimasho** [comment]
I've re-arranged the media view controls and close button fit in the new layout.
