### ISSUE TITLE
ability/option to have full res images in the image grid gallery

### ISSUE THREAD

**Issue by greenscarf07** [qimasho/thread-media-viewer#2]
I'm not entirely sure if this is already possible, but it would be nice if there was the ability/option to have full res images in the gallery grid instead of just the thumbnail sizes

**Comment by qimasho** [comment]
I want to be a good citizen, so I don't see myself implementing anything like this. It would cause a lot of load on the server, just to increase the quality of thumbnails a bit. Also, the time it'd take for all images in a thread to load at the same time would be significant, and you wouldn't be able to view anything, because opening any image would be slowed down by every other image loading as well.

I might add a feature to preload stuff, but that will be a manual button to be used when necessary (sometimes it takes forever for stuff to start loading, so preloading would be nice), and it will gently preload a couple things at a time. Definitely not anything that will basically DDOS a CDN every time you open a thread, which might potentially even lead to a ban when the website decides you are an inconsiderate content scraper.

**Comment by MoneyAllDay** [comment]
@qimasho Since you mentioned preloading i just came here to suggest preloading the next image in the gallery would be a nice addition so you don't have to wait for it to load.

It would be good both for users and the server because users would not have to wait for the next image load and for the server because all the user will "bandwidth" more is just 1 extra image. Maybe add an option for how many images we could preload.

![1](https://user-images.githubusercontent.com/19583547/113219839-158a9080-927a-11eb-9069-ca8c71c78290.gif)
